series: demo-amazonreviews-labelshift
artifact_storage_uri: /home/ssc/Entwicklung/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /home/ssc/Entwicklung/projects/arguseyes/arguseyes/example_pipelines/amazon-reviews__label-shift.py
  working_directory: /home/ssc/Entwicklung/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
    - label_shift
