series: arguseyes-demo-dryrun
artifact_storage_uri: /Users/ssc/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/paper-example.py
  args:
    - Digital_Video_Games
    - !!str 2015-08-01
  working_directory: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
     - traintest_overlap
